# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-24 18:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story_api_id', models.CharField(max_length=512, unique=True, verbose_name='Story API ID')),
                ('name', models.CharField(max_length=512)),
                ('date', models.DateField()),
                ('image_url', models.URLField(max_length=1024, verbose_name='Featured Image URL')),
                ('audio_url', models.URLField(max_length=1024, verbose_name='MP3 File URL')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('name', models.CharField(max_length=512)),
                ('story_api_tag_id', models.CharField(help_text='Used to pull in episodes.         Consult NPR Digital to get this activated on your site.', max_length=150, verbose_name='NPR Story API Tag ID')),
                ('story_api_org_id', models.CharField(help_text='Your OrgID for the NPR Story API.                   Without this, the tool will be unable to pull in episodes.', max_length=150, verbose_name='NPR Story API Org ID')),
                ('text', models.TextField()),
                ('image', models.ImageField(upload_to='shows/images')),
                ('custom_banner', models.FileField(blank=True, null=True, upload_to='shows/banners')),
                ('feed_url', models.URLField(blank=True, max_length=1024, null=True, verbose_name='Podcast (RSS) Feed URL')),
                ('itunes_url', models.URLField(blank=True, max_length=1024, null=True, verbose_name='Apple Podcasts/iTunes Page URL')),
                ('stitcher_url', models.URLField(blank=True, max_length=1024, null=True, verbose_name='Stitcher Page URL')),
                ('google_url', models.URLField(blank=True, max_length=1024, null=True, verbose_name='Google Play Podcasts Page URL')),
                ('overcast_url', models.URLField(blank=True, max_length=1024, null=True, verbose_name='Overcast Page URL')),
                ('pocket_casts_url', models.URLField(blank=True, max_length=1024, null=True, verbose_name='Pocket Casts Page URL')),
                ('npr_one_url', models.URLField(blank=True, max_length=1024, null=True, verbose_name='NPR One URL')),
            ],
            options={
                'ordering': ['slug'],
            },
        ),
        migrations.AddField(
            model_name='episode',
            name='show',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='shows.Show'),
        ),
    ]
