# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-30 17:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0002_auto_20180730_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='image_alt',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='episode',
            name='image_caption',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='episode',
            name='image_credit',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AddField(
            model_name='episode',
            name='image_source',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name='episode',
            name='text',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
