# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-31 13:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0003_auto_20180730_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='canonical_url',
            field=models.URLField(blank=True),
        ),
    ]
