# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-31 16:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0004_episode_canonical_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='social_tagline',
            field=models.TextField(blank=True),
        ),
    ]
